### ISSUE TITLE
Too few arguments to function RoomController::index_action()

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [elan-ev/studip-meeting#436]
Following error appears often in our nginx error log:

```
2022/11/13 19:45:33 [error] 2156246#2156246: *855153963 FastCGI sent in stderr: "PHP message: ArgumentCountError: Too few arguments to function RoomController::index_action(), 1 passed in /srv/studip_git/vendor/trails/trails.php on line 557 and exactly 2 expected in /srv/studip_git/public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/room.php:61
Stack trace:
#0 /srv/studip_git/vendor/trails/trails.php(557): RoomController->index_action('')
#1 /srv/studip_git/app/controllers/studip_controller.php(110): Trails_Controller->perform('index/')
#2 /srv/studip_git/vendor/trails/trails.php(154): StudipController->perform('index/')
#3 /srv/studip_git/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('room/index/')
#4 /srv/studip_git/public/plugins_packages/elan-ev/MeetingPlugin/MeetingPlugin.php(254): Trails_Dispatcher->dispatch('room/index/')
#5 /srv/studip_git/public/plugins.php(54): MeetingPlugin->perform('room/index/')
#6 {main}" while reading response header from upstream, client: xxx, server: [studip.uni-hannover.de](http://studip.uni-hannover.de/), request: "GET /plugins.php/meetingplugin/room/index/ HTTP/2.0", upstream: "[fastcgi://unix:/run/php/php-fpm-studip.sock:](fastcgi://unix/run/php/php-fpm-studip.sock:)", host: "[studip.uni-hannover.de](http://studip.uni-hannover.de/)"
```

**Comment by schuettloeffel-elsa** [comment]
This would be 2.69

**Comment by ferishili** [comment]
Have you considered or do you have the possibility to upgrade to v2.70 and check if the problem still exists?

**Comment by ferishili** [comment]
Sorry to hear that, I have tried my best to make that as easy as possible with no difficulties/errors. Please let me know, what makes it difficult for you to upgrade to 2.70, so we can improve it.

**Comment by ferishili** [comment]
I am closing this issue, in a favor of an easy and smooth upgrade :D
