### ISSUE TITLE
In 5.3 kaputt

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [elan-ev/studip-meeting#439]
In einer Stud.IP 5.3 kommt folgender Fehler:

```
Typ: RuntimeException
Nachricht: Method _ does not exist
Code: 0
Stack trace:
#$ public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/index.php(104)
#0 public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/index.php(262): IndexController->__call('_', Array)
#1 public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/index.php(144): IndexController->getHelpbarContent('main')
#2 vendor/trails/trails.php(557): IndexController->index_action()
#3 app/controllers/studip_controller.php(119): Trails_Controller->perform('')
#4 vendor/trails/trails.php(154): StudipController->perform('')
#5 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('index')
#6 public/plugins_packages/elan-ev/MeetingPlugin/MeetingPlugin.php(254): Trails_Dispatcher->dispatch('index')
#7 public/plugins.php(61): MeetingPlugin->perform('index')
#8 {main}
```

**Comment by schuettloeffel-elsa** [comment]
Hei @ferishili, we plan to upgrade our stud.ip to 5.3 in march, is it possible for you to fix that issue in time? Would be great!

**Comment by ferishili** [comment]
Hi, I would say yes, the problem will be fixed in the next release which is planned for that time!

**Comment by schuettloeffel-elsa** [comment]
Great, do you have a more specific date? We would need to test the new version I think at least in mid february; otherwise we would need to do a hotfix for our current version.

**Comment by ferishili** [comment]
Unfortunately not at the moment, additionally, I am going start working of the new release in march, therefore, I don't think that could be suitable for your timeline!
In this case, I will try to come up with a patch for this issue.

**Comment by schuettloeffel-elsa** [comment]
Thanks a lot!

**Comment by schuettloeffel-elsa** [comment]
Sorry, just to get this clear: does that mean you will provide a patch for the current version till mid feb?

**Comment by ferishili** [comment]
Hi, I am afraid, there is a change to the plan, because I am injured and unable to work, therefore, the start of this project will be postponed. Sorry for any inconvenience.

**Comment by schuettloeffel-elsa** [comment]
No worries, André got that fixed for us :) Get well soon!

**Comment by schuettloeffel-elsa** [comment]
FYI: this is the fix: https://github.com/schuettloeffel-elsa/studip-meeting/pull/2

**Comment by ferishili** [comment]
Hi @schuettloeffel-elsa,
Thanks for your contribution
